branches:
  - release

verifyConditions:
  - '@semantic-release/git'
  - '@semantic-release/github'

generateNotes:
  - '@semantic-release/release-notes-generator'

prepare:
  - path: '@semantic-release/changelog'
    changelogFile: 'CHANGELOG.md'
    changelogTitle: 'Changelog'
  - path: '@semantic-release/git'
    assets: ['CHANGELOG.md']

success:
  - '@semantic-release/github'

fail:
  - '@semantic-release/github'
